 Vagrant.configure("2") do |config|

  config.vm.define :dev1 do |dev1|

    dev1.vm.box = "ubuntu/focal64"
    dev1.vm.box_check_update = true
    dev1.disksize.size = "200GB"
    dev1.vm.provider :virtualbox do |vb|
      vb.name = "sonarqube-docker-vm"
      vb.memory = 16384
      vb.cpus = 2
    end
    dev1.vm.network "private_network", ip: "192.168.33.10"
    dev1.vm.synced_folder "./scripts", "/vagrant"
    #dev1.vm.provision "shell", inline: <<-SHELL
    #  mkdir -p /etc/docker
    #  cp -f /vagrant/docker/daemon.json /etc/docker/daemon.json
    #SHELL
    dev1.vm.provision :docker
    dev1.vm.provision :docker_compose

  end

end