version: '3.7'

services:
  
  dockeragent1:
    hostname: dockeragent1
    #image: vagrant_dockeragent1
    build: 
      context: ./inits
      dockerfile: Dockerfile.agent
    container_name: dockeragent1
    restart: unless-stopped
    volumes:
      - './inits/daemon.json:/etc/docker/daemon.json'
      - './inits/settings.xml:/root/.m2/settings.xml'
      - './inits/sonar-scanner.properties:/azp/sonarscanner/sonar-scanner-4.6.2.2472-linux/conf/sonar-scanner.properties'
      # Access Docker socket inside the Docker Container.
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/usr/local/bin/docker:/usr/local/bin/docker'
    environment:
      - "JAVA_HOME=/usr/lib/jvm/jre-11-openjdk/"
      - "AZP_URL=http://domain.company.com.tr:8080/tfs/collection_name/"
      - "AZP_POOL=pool_name"
      - "AZP_USERNAME=username"
      - "AZP_PASSWORD=password"
  