FROM ubuntu:18.04

# To make it easier for build and release pipelines to run apt-get,
# configure apt to not require confirmation (assume the -y argument by default)
ENV DEBIAN_FRONTEND=noninteractive
RUN echo "APT::Get::Assume-Yes \"true\";" > /etc/apt/apt.conf.d/90assumeyes

# Update and Upgrade Ubuntu 18.04
RUN apt-get update \
  && apt-get upgrade -y --no-install-recommends 

# Install Required Dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
        apt-transport-https \
        gnupg-agent \
        wget \
        unzip \
        tree \
        vim \
        git

# GCC and CPP Installations
RUN apt-get install -y --no-install-recommends \
        build-essential \
        software-properties-common \
        libc6-dev \
        gcc \
        g++ \
        cpp \
        dpkg-dev \
        make \
        cmake

# Python2 and Python3 Installations
RUN apt-get install -y --no-install-recommends \
        python \
        python-dev \
        python3 \
        python3-dev \
        python3-pip \
        virtualenv \
        libssl-dev \
        libffi-dev 

# NodeJS 14 LTS Installation
WORKDIR /azp/nodejs
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get update
RUN apt-get install -y nodejs

# Java JDK 11 Installation and JAVA_HOME Environment Variable Set
RUN apt-get install -y --no-install-recommends openjdk-11-jdk 
RUN export JAVA_HOME=$(readlink -f /usr/bin/javac | sed "s:/bin/javac::")
#RUN export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
RUN export PATH=$PATH:$JAVA_HOME/bin

# Maven 3.8.1 Installation
RUN apt-get install -y --no-install-recommends maven
WORKDIR /azp/maven
RUN wget https://ftp.itu.edu.tr/Mirror/Apache/maven/maven-3/3.8.1/binaries/apache-maven-3.8.1-bin.tar.gz
RUN tar -xvzf apache-maven-3.8.1-bin.tar.gz \
  && mv apache-maven-3.8.1 maven \
  && mv /usr/share/maven /usr/share/maven-old \ 
  && mv maven /usr/share/
RUN rm -rf /azp/maven/apache-maven-3.8.1-bin.tar.gz

# SonarScanner 4.6.2.2472 Installation
WORKDIR /azp/sonarscanner
RUN wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip
RUN unzip sonar-scanner-cli-4.6.2.2472-linux.zip
RUN export PATH=${PATH}:/azp/sonarscanner/sonar-scanner-4.6.2.2472-linux/bin
RUN rm -rf /azp/sonarscanner/sonar-scanner-cli-4.6.2.2472-linux.zip

# Install Azure DevOps Required Dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    jq \
    iputils-ping \
    libcurl4 \
    libicu60 \
    libunwind8 \
    netcat \
    libssl1.0 \
  && rm -rf /var/lib/apt/lists/*

RUN curl -LsS https://aka.ms/InstallAzureCLIDeb | bash \
  && rm -rf /var/lib/apt/lists/*

# Azure DevOps Agent Environment Variables
ENV AGENT_ALLOW_RUNASROOT=1
ENV AZP_AGENT_NAME=azure_devops_agent
ENV AZP_URL=http://domain.company.com.tr:8080/tfs/collection_name/
ENV AZP_POOL=pool_name
ENV AZP_TOKEN=token
ENV AZP_USERNAME=username
ENV AZP_PASSWORD=password

# Azure DevOps Agent Installation
ARG TARGETARCH=amd64
ARG AGENT_VERSION=2.153.1
WORKDIR /azp/agent
RUN if [ "$TARGETARCH" = "amd64" ]; then \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-x64-${AGENT_VERSION}.tar.gz; \
    else \
      AZP_AGENTPACKAGE_URL=https://vstsagentpackage.azureedge.net/agent/${AGENT_VERSION}/vsts-agent-linux-${TARGETARCH}-${AGENT_VERSION}.tar.gz; \
    fi; \
    curl -LsS "$AZP_AGENTPACKAGE_URL" | tar -xz
RUN ./bin/installdependencies.sh

# Cleanup Ubuntu Environment
RUN apt-get autoremove & apt-get autoclean & apt-get clean

# Azure DevOps Agent Starting
WORKDIR /azp
COPY ./start.sh .
RUN chmod +x start.sh

ENTRYPOINT [ "./start.sh" ]